// Downloads the exact woff2 files for our type stack from Google Fonts and
// generates a self-hosted @font-face stylesheet (no runtime request to Google).
// Run: node scripts/fetch-fonts.mjs
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = resolve(root, "docs/assets/fonts");
const cssOut = resolve(root, "docs/assets/css/fonts.css");

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&family=Space+Mono:wght@400;700&display=swap";
// A modern desktop UA makes Google return woff2 with unicode-range subsets.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const slug = (s) => s.toLowerCase().replace(/\s+/g, "-");

async function main() {
  await mkdir(fontsDir, { recursive: true });
  const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

  // Split into @font-face blocks, each preceded by a /* subset */ comment.
  const blocks = css.split("@font-face").slice(1);
  let currentSubset = "latin";
  const faces = [];
  // Re-parse with the leading comment captured per block.
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]+)}/g;
  let m;
  while ((m = re.exec(css))) {
    const subset = m[1];
    const body = m[2];
    if (subset !== "latin") continue; // latin covers German umlauts (U+0000–00FF)
    const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1];
    const style = /font-style:\s*(\w+)/.exec(body)?.[1] || "normal";
    const url = /src:\s*url\(([^)]+)\)/.exec(body)?.[1];
    if (!family || !weight || !url) continue;
    faces.push({ family, weight, style, url });
  }

  const out = [
    "/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs. Do not edit by hand. */",
  ];
  for (const f of faces) {
    const file = `${slug(f.family)}-${f.weight}.woff2`;
    const buf = Buffer.from(await (await fetch(f.url, { headers: { "User-Agent": UA } })).arrayBuffer());
    await writeFile(resolve(fontsDir, file), buf);
    out.push(
      `@font-face{font-family:'${f.family}';font-style:${f.style};font-weight:${f.weight};font-display:swap;src:url('../fonts/${file}') format('woff2');}`
    );
    console.log(`✓ ${file} (${buf.length} bytes)`);
  }
  await writeFile(cssOut, out.join("\n") + "\n");
  console.log(`\nWrote ${cssOut} with ${faces.length} @font-face rules.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
